baseurl = "http://frontend.github.io/toolbox/"
languageCode = "en-us"
title = "Toolbox"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Antistatique"
	description = "A styleguide generator with Gulp and React"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/frontend/generator-toolbox"

	version = "2.0.2"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "antistatique"
	github  = "frontend"
	email   = "dev@antistatique.net"

[[menu.main]]
	name   = "Toolbox"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "The styleguide generator"
	url    = "toolbox/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

